apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: locadora-jogos
data:
  spring.datasource.url: "jdbc:mysql://mysql-service:3306/locadora_jogos"
  spring.jpa.hibernate.ddl-auto: "validate"
  spring.jpa.show-sql: "false"
