apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: locadora-jogos
type: Opaque
stringData:
  spring.datasource.username: "root"
  spring.datasource.password: "locadora123"
  mysql.root.password: "locadora123"
